### ISSUE TITLE
Firebase Authentication

### ISSUE THREAD

**Issue by the-matrix-admin** [the-matrix-admin/the-budget-manager#2]
### General purpose
By using Firebase Auth implement authentication service in the application. 
Firebase Auth takes care of Sign In, Sign Up, Session and User Storage, 3rd party providers like Google, Facebook, GitHub.

### Tasks:

- [ ] Create Firebase Console Project
- [ ] Enable Authentication Services
- [ ] For now allow for registration with email and password (no activation)
- [ ] Connect the application with Firebase (by adding .env file)
